In [1]:
import pandas as pd 
import numpy as np 
import os

In [2]:
dir = "synthea-mimic/csv"
for file in os.listdir(dir):
    print(dir, file)
    data = pd.read_csv(os.path.join(dir, file), on_bad_lines='skip')
    print(file)
    print(data.columns)
    print()

synthea-mimic/csv allergies.csv
allergies.csv
Index(['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'SYSTEM',
       'DESCRIPTION', 'TYPE', 'CATEGORY', 'REACTION1', 'DESCRIPTION1',
       'SEVERITY1', 'REACTION2', 'DESCRIPTION2', 'SEVERITY2'],
      dtype='object')

synthea-mimic/csv careplans.csv
careplans.csv
Index(['Id', 'START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION',
       'REASONCODE', 'REASONDESCRIPTION'],
      dtype='object')

synthea-mimic/csv claims.csv
claims.csv
Index(['Id', 'PATIENTID', 'PROVIDERID', 'PRIMARYPATIENTINSURANCEID',
       'SECONDARYPATIENTINSURANCEID', 'DEPARTMENTID', 'PATIENTDEPARTMENTID',
       'DIAGNOSIS1', 'DIAGNOSIS2', 'DIAGNOSIS3', 'DIAGNOSIS4', 'DIAGNOSIS5',
       'DIAGNOSIS6', 'DIAGNOSIS7', 'DIAGNOSIS8', 'REFERRINGPROVIDERID',
       'APPOINTMENTID', 'CURRENTILLNESSDATE', 'SERVICEDATE',
       'SUPERVISINGPROVIDERID', 'STATUS1', 'STATUS2', 'STATUSP',
       'OUTSTANDING1', 'OUTSTANDING2', 'OUTSTANDINGP', 'LASTBILLEDDATE1',
       'LASTBILLEDDATE2', 'LASTBILLEDDATEP', 'HEALTHCARECLAIMTYPEID1',
       'HEALTHCARECLAIMTYPEID2'],
      dtype='object')

synthea-mimic/csv claims_transactions.csv
claims_transactions.csv
Index(['ID', 'CLAIMID', 'CHARGEID', 'PATIENTID', 'TYPE', 'AMOUNT', 'METHOD',
       'FROMDATE', 'TODATE', 'PLACEOFSERVICE', 'PROCEDURECODE', 'MODIFIER1',
       'MODIFIER2', 'DIAGNOSISREF1', 'DIAGNOSISREF2', 'DIAGNOSISREF3',
       'DIAGNOSISREF4', 'UNITS', 'DEPARTMENTID', 'NOTES', 'UNITAMOUNT',
       'TRANSFEROUTID', 'TRANSFERTYPE', 'PAYMENTS', 'ADJUSTMENTS', 'TRANSFERS',
       'OUTSTANDING', 'APPOINTMENTID', 'LINENOTE', 'PATIENTINSURANCEID',
       'FEESCHEDULEID', 'PROVIDERID', 'SUPERVISINGPROVIDERID'],
      dtype='object')

synthea-mimic/csv conditions.csv
conditions.csv
Index(['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'SYSTEM', 'CODE',
       'DESCRIPTION', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10'],
      dtype='object')

synthea-mimic/csv devices.csv
devices.csv
Index(['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'UDI'], dtype='object')

synthea-mimic/csv encounters.csv
encounters.csv
Index(['Id', 'START', 'STOP', 'PATIENT', 'ORGANIZATION', 'PROVIDER', 'PAYER',
       'ENCOUNTERCLASS', 'CODE', 'DESCRIPTION', 'BASE_ENCOUNTER_COST',
       'TOTAL_CLAIM_COST', 'PAYER_COVERAGE', 'REASONCODE',
       'REASONDESCRIPTION'],
      dtype='object')

synthea-mimic/csv imaging_studies.csv
imaging_studies.csv
Index(['Id', 'DATE', 'PATIENT', 'ENCOUNTER', 'SERIES_UID', 'BODYSITE_CODE',
       'BODYSITE_DESCRIPTION', 'MODALITY_CODE', 'MODALITY_DESCRIPTION',
       'INSTANCE_UID', 'SOP_CODE', 'SOP_DESCRIPTION', 'PROCEDURE_CODE'],
      dtype='object')

synthea-mimic/csv immunizations.csv
immunizations.csv
Index(['DATE', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST'], dtype='object')

synthea-mimic/csv medications.csv
medications.csv
Index(['START', 'STOP', 'PATIENT', 'PAYER', 'ENCOUNTER', 'CODE', 'DESCRIPTION',
       'BASE_COST', 'PAYER_COVERAGE', 'DISPENSES', 'TOTALCOST', 'REASONCODE',
       'REASONDESCRIPTION'],
      dtype='object')

synthea-mimic/csv observations.csv
observations.csv
Index(['DATE', 'PATIENT', 'ENCOUNTER', 'CATEGORY', 'CODE', 'DESCRIPTION',
       'VALUE', 'UNITS', 'TYPE'],
      dtype='object')

synthea-mimic/csv organizations.csv
organizations.csv
Index(['Id', 'NAME', 'ADDRESS', 'CITY', 'STATE', 'ZIP', 'LAT', 'LON', 'PHONE',
       'REVENUE', 'UTILIZATION'],
      dtype='object')

synthea-mimic/csv patients.csv
patients.csv
Index(['Id', 'BIRTHDATE', 'DEATHDATE', 'SSN', 'DRIVERS', 'PASSPORT', 'PREFIX',
       'FIRST', 'MIDDLE', 'LAST', 'SUFFIX', 'MAIDEN', 'MARITAL', 'RACE',
       'ETHNICITY', 'GENDER', 'BIRTHPLACE', 'ADDRESS', 'CITY', 'STATE',
       'COUNTY', 'FIPS', 'ZIP', 'LAT', 'LON', 'HEALTHCARE_EXPENSES',
       'HEALTHCARE_COVERAGE', 'INCOME'],
      dtype='object')

synthea-mimic/csv payer_transitions.csv
payer_transitions.csv
Index(['PATIENT', 'MEMBERID', 'START_DATE', 'END_DATE', 'PAYER',
       'SECONDARY_PAYER', 'PLAN_OWNERSHIP', 'OWNER_NAME'],
      dtype='object')

synthea-mimic/csv procedures.csv
procedures.csv
Index(['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'SYSTEM', 'CODE',
       'DESCRIPTION', 'BASE_COST', 'REASONCODE', 'REASONDESCRIPTION'],
      dtype='object')

synthea-mimic/csv providers.csv
providers.csv
Index(['Id', 'ORGANIZATION', 'NAME', 'GENDER', 'SPECIALITY', 'ADDRESS', 'CITY',
       'STATE', 'ZIP', 'LAT', 'LON', 'ENCOUNTERS', 'PROCEDURES'],
      dtype='object')

synthea-mimic/csv supplies.csv
supplies.csv
Index(['DATE', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'QUANTITY'], dtype='object')

In [3]:
data = pd.DataFrame()

data_files_and_columns = {
    'patients.csv': ['Id', 'DEATHDATE', 'BIRTHDATE', 'GENDER', 'INCOME'],
    'conditions.csv': ['PATIENT'],
    'medications.csv': ['PATIENT'],
    'procedures.csv': ['PATIENT'],
    'encounters.csv': ['PATIENT']
}

for file, columns in data_files_and_columns.items():
    _data = pd.read_csv(os.path.join(dir, file), usecols=columns, on_bad_lines='skip')
    #print(_data)
    if file == 'patients.csv':
        data = _data
    else:
        name = file.split('.')[0].upper()
        print(name)
        count_data = _data['PATIENT'].value_counts()
        count_data = count_data.rename(name+'_COUNT')
        data = pd.merge(data, count_data, left_on='Id', right_on='PATIENT', how='outer')
        #data.drop('PATIENT', axis=1, inplace=True)
data

CONDITIONS
MEDICATIONS
PROCEDURES
ENCOUNTERS

,Id,BIRTHDATE,DEATHDATE,GENDER,INCOME,CONDITIONS_COUNT,MEDICATIONS_COUNT,PROCEDURES_COUNT,ENCOUNTERS_COUNT
0,00043074-bbc9-7d65-195e-e615d7b61dcb,1979-12-27,NaN,F,123712,NaN,20.0,129.0,67.0
1,0033b4c0-255c-af66-8fc9-ebe17f725461,1994-03-18,NaN,F,214184,NaN,6.0,62.0,26.0
2,0050e373-575d-88b8-f682-64abf43ae57e,2008-06-02,NaN,M,85952,24.0,9.0,115.0,38.0
3,0054eccc-84f7-ff56-75cf-d4dc86f63a7a,2013-07-27,NaN,M,42496,NaN,7.0,70.0,28.0
4,00a56f5f-4707-007f-9132-bf26fd1ceee8,2007-07-07,NaN,F,29343,NaN,63.0,195.0,89.0
...,...,...,...,...,...,...,...,...,...
3200,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN
3201,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN
3202,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
3203,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN
3204,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN

In [4]:
data['MORTALITY'] = [0 if pd.isna(x) else 1 for x in data['DEATHDATE']]
data.drop(['DEATHDATE'], axis=1, inplace=True)
data

,Id,BIRTHDATE,GENDER,INCOME,CONDITIONS_COUNT,MEDICATIONS_COUNT,PROCEDURES_COUNT,ENCOUNTERS_COUNT,MORTALITY
0,00043074-bbc9-7d65-195e-e615d7b61dcb,1979-12-27,F,123712,NaN,20.0,129.0,67.0,0
1,0033b4c0-255c-af66-8fc9-ebe17f725461,1994-03-18,F,214184,NaN,6.0,62.0,26.0,0
2,0050e373-575d-88b8-f682-64abf43ae57e,2008-06-02,M,85952,24.0,9.0,115.0,38.0,0
3,0054eccc-84f7-ff56-75cf-d4dc86f63a7a,2013-07-27,M,42496,NaN,7.0,70.0,28.0,0
4,00a56f5f-4707-007f-9132-bf26fd1ceee8,2007-07-07,F,29343,NaN,63.0,195.0,89.0,0
...,...,...,...,...,...,...,...,...,...
3200,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,0
3201,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,0
3202,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,0
3203,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,0
3204,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,0

In [5]:
data = data.dropna(subset=['Id'])

In [6]:
data = data.replace(np.nan, 0)
data

,Id,BIRTHDATE,GENDER,INCOME,CONDITIONS_COUNT,MEDICATIONS_COUNT,PROCEDURES_COUNT,ENCOUNTERS_COUNT,MORTALITY
0,00043074-bbc9-7d65-195e-e615d7b61dcb,1979-12-27,F,123712,0.0,20.0,129.0,67.0,0
1,0033b4c0-255c-af66-8fc9-ebe17f725461,1994-03-18,F,214184,0.0,6.0,62.0,26.0,0
2,0050e373-575d-88b8-f682-64abf43ae57e,2008-06-02,M,85952,24.0,9.0,115.0,38.0,0
3,0054eccc-84f7-ff56-75cf-d4dc86f63a7a,2013-07-27,M,42496,0.0,7.0,70.0,28.0,0
4,00a56f5f-4707-007f-9132-bf26fd1ceee8,2007-07-07,F,29343,0.0,63.0,195.0,89.0,0
...,...,...,...,...,...,...,...,...,...
2820,ff80137d-8184-4ee6-a6d6-c5f567d61c44,1944-06-06,F,80165,0.0,7.0,122.0,37.0,0
2821,ff91eb41-7717-d1f8-7119-b87035f8f0b9,1952-01-31,F,70463,45.0,62.0,149.0,42.0,0
2822,ff9d79a3-78a7-152c-4a78-080617428249,2002-10-14,M,144547,0.0,1.0,60.0,16.0,0
2823,ffc5d3f8-ce27-e72f-ec38-a0c250cb6833,1972-03-12,F,55777,0.0,7.0,86.0,41.0,0
2824,ffc8bfa4-30fc-ec56-53ac-9f96a8ee482c,2020-07-04,M,10609,0.0,4.0,20.0,20.0,0

In [7]:
data.value_counts('MORTALITY')

MORTALITY
0    2456
1     369
Name: count, dtype: int64

In [8]:
data.to_csv('dataset.csv', index=False)